name = "Lax345332"
defaultTargets = ["Lax345332"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax434930"
git = "https://github.com/EdouardBonnet/classical-complexity"
rev = "0c0840319318215fd7b36a9a822b81ce55cf6941"
subDir = "concepts"

[[require]]
name = "Lax429075"
git = "https://github.com/EdouardBonnet/cook-levin"
rev = "905f2da2698d5b38002676f74632aa716e731389"
subDir = "concepts"

[[lean_lib]]
name = "Lax345332"
